### ISSUE TITLE
propagate full beamline using different propagator for each element

### ISSUE THREAD

**Issue by srio** [oasys-kit/wofry#2]
If want to propagate a beamline containing several elements I do: 
1) Initialize propagator and add the specific propagator(s) to be used: 

```
    from wofry.propagator.propagators2D.fresnel_zoom_xy import FresnelZoomXY2D
    from wofry.propagator.propagator import PropagationManager

    propagator = PropagationManager.Instance()
    propagator.add_propagator(FresnelZoomXY2D())

```

2) Define the beamline elements: 
```
    from syned.beamline.beamline_element import BeamlineElement
    from syned.beamline.element_coordinates import ElementCoordinates

    beamline_element1 = BeamlineElement(optical_element=optical_element,coordinates=ElementCoordinates(
        p=36.0,q=0))

    beamline_element2 = etc. 
```

3) Store the beamline elements to PropagationElements:
```
    from wofry.propagator.propagator import PropagationElements
    propagation_elements = PropagationElements()
    propagation_elements.add_beamline_element(beamline_element1)
    propagation_elements.add_beamline_element(beamline_element2) # etc etc

```

4) Store in PropagationParameters the incident wavefront, beamline elements and additional parameters:

```
    from wofry.propagator.propagator import PropagationParameters
    propagation_parameters = PropagationParameters(wavefront=input_wavefront.duplicate(),propagation_elements = propagation_elements)

    propagation_parameters.set_additional_parameters('shift_half_pixel', 1)
    propagation_parameters.set_additional_parameters('magnification_x', magnification_x)
    propagation_parameters.set_additional_parameters('magnification_y', magnification_y)
```

5) Do the propagation: 
```
    output_wavefront = propagator.do_propagation(propagation_parameters=propagation_parameters,handler_name='FRESNEL_ZOOM_XY_2D')
```

The limitation of this approach is that the same propagator (FRESNEL_ZOOM_XY_2D) and the same parameters (magnification_x, etc.) apply to all individual propagations (there are two times the number of element propagations). This forces me to split the propagation and do it element by element. 

What I want is to propagate the full beamline with the possibility to define a different propagator per element and different parameters (like magnification). 

Would be possible to upgrade propagator to do that? Ideally something like (for a two-element beamline): 

```
output_wavefront = propagator.do_propagation(propagation_parameters=propagation_parameters,handler_name=['FRESNEL_ZOOM_XY_2D','FRESNEL_ZOOM_XY_2D'],additional_parameters=[{"magnification_x":0.1,"magnification_y":0.1},{"magnification_x":1.5,"magnification_y":3.5}])
```
Indeed, the "additional parameters" (e.g. magnification_x) are mostly related to the specific propagator (FRESNEL_ZOOM_XY_2D) so it does not make much sense to store them with "set_additional_parameters" to the ball containing the source and beamline. 

How to find an elegant solution consistent with our structure?

**Comment by lucarebuffi** [comment]
I modified the PropagationElements object, by adding the possibility of indicating some specific propagations parameters for every beamline elements (by default None, so the current implementation is untouched)

```
class PropagationElements(object):
    
    INSERT_AFTER = 0
    INSERT_BEFORE = 1

    def __init__(self):
        self.__propagation_elements = []
        self.__propagation_element_parameters = []

    def add_beamline_element(self, beamline_element=BeamlineElement(), element_parameters=None):
        if beamline_element is None: raise ValueError("Beamline is None")

        self.__propagation_elements.append(beamline_element)
        self.__propagation_element_parameters.append(element_parameters)

    def add_beamline_elements(self, beamline_elements=[], element_parameters_list=None):
        if beamline_elements is None: raise ValueError("Beamline is None")
        
        if not element_parameters_list is None:
            if len(beamline_elements) != len(element_parameters_list): raise ValueError("Specific Parameters list does not match Beamline Elements list")
        else:
            element_parameters_list = [None]*len(beamline_elements)
            
        for beamline_element, element_parameters in zip(beamline_elements, element_parameters_list):
            self.add_beamline_element(beamline_element, element_parameters)
        
    def insert_beamline_element(self, index, new_element=BeamlineElement(), mode=INSERT_BEFORE, new_element_parameters=None):
        if mode == PropagationElements.INSERT_BEFORE:
            if index == 0:
                self.__propagation_elements = [new_element] + self.__propagation_elements
                self.__propagation_element_parameters = [new_element_parameters]
            else:
                self.__propagation_elements.insert(index, new_element)
                self.__propagation_element_parameters.insert(index, new_element_parameters)
        elif mode == PropagationElements.INSERT_AFTER:
            if index == len(self.__propagation_elements) - 1:
                self.__propagation_elements = self.__propagation_elements + [new_element]
                self.__propagation_element_parameters = self.__propagation_element_parameters + [new_element_parameters]
            else:
                self.__propagation_elements.insert(index+1, new_element)
                self.__propagation_element_parameters.insert(index+1, new_element_parameters)

    def get_propagation_elements_number(self):
        return len(self.__propagation_elements)

    def get_propagation_elements(self):
        return self.__propagation_elements

    def get_propagation_element(self, index):
        return self.__propagation_elements[index]

    def get_propagation_elements_specific_parameters(self):
        return self.__propagation_element_parameters

    def get_propagation_element_specific_parameter(self, index):
        return self.__propagation_element_parameters[index]
```

With this implementation, your example becomes:

```
    from wofry.propagator.propagator import PropagationElements
    from wofry.propagator.propagator import PropagationParameters

    propagation_elements = PropagationElements()

    element1_parameters = {'shift_half_pixel' : 1, 
                           'magnification_x': magnification_x1, 
                           'magnification_y': magnification_y1}
    element2_parameters = {'shift_half_pixel' : 1, 
                           'magnification_x': magnification_x2, 
                           'magnification_y': magnification_y2}

    propagation_elements.add_beamline_element(beamline_element1, element1_parameters)
    propagation_elements.add_beamline_element(beamline_element2, element2_parameters) # etc etc

    propagation_parameters = PropagationParameters(wavefront=input_wavefront.duplicate(),propagation_elements = propagation_elements)
```

This is a simple "quick and dirty" implementation, by using a dictionary as a possibile object. In principle, the specific parameters are everything, since they depend from the actual implementation of the propagator you want to use. We can also decide to implement a wrapper of a dictionary with a dedicated name, instead, but, probably, is useless.

In the specific propagator code, you will access the parameters as follow:

```
 def do_propagation(self, parameters=PropagationParameters()):
        wavefront = parameters.get_wavefront()

        propagation_elements = parameters.get_PropagationElements()
        for element, parameters in zip(propagation_elements.get_propagation_elements(),
                                       propagation_elements.get_propagation_elements_parameters()) :
            coordinates = element.get_coordinates()
            shift_half_pixel = parameters['shift_half_pixel']
            magnification_x = parameters['magnification_x']
            magnification_y = parameters['magnification_y']
```

**Comment by srio** [comment]
OK, beautiful. 

Now, there are two ways of defining specific parameters, the former one (via set_additional_parameters method) and the new one (stored with the beamline elements). To make the new one available by the specific propagator (via its method do_specific_propagation) without changing anything therein I modified Propagator.do_propagator to set the new additional parameters into the old way. This is the old version: 
'''
def do_propagation(self, parameters=PropagationParameters()):
       
        wavefront = parameters.get_wavefront()
        for element in parameters.get_PropagationElements().get_propagation_elements():
            coordinates = element.get_coordinates()

            if coordinates.p() != 0.0: wavefront = self.do_specific_progation_before(wavefront, coordinates.p(), parameters)
            wavefront = element.get_optical_element().applyOpticalElement(wavefront, parameters)
            if coordinates.q() != 0.0: wavefront = self.do_specific_progation_after(wavefront, coordinates.q(), parameters)

        return wavefront
'''


to this is the new one: 

'''

    def do_propagation(self, parameters=PropagationParameters()):
        wavefront = parameters.get_wavefront()

        propagation_elements = parameters.get_PropagationElements()
        for element, parameters2 in zip(propagation_elements.get_propagation_elements(),
                                       propagation_elements.get_propagation_elements_parameters()) :
            coordinates = element.get_coordinates()
            if parameters2 is not None:
                # the specific propagator parameters defined for each element are now stored.
                # They overwrite the ones defined with the mechanism "set_additional_parameters" (if exist)
                # note that they remain set for this element and next ones (so the set_additional_parameters
                #   mechanism cannot be used as a default)
                for key in parameters2.keys():
                    parameters.set_additional_parameters(key, parameters2[key])

            if coordinates.p() != 0.0: wavefront = self.do_specific_progation_before(wavefront, coordinates.p(), parameters)
            wavefront = element.get_optical_element().applyOpticalElement(wavefront, parameters)
            if coordinates.q() != 0.0: wavefront = self.do_specific_progation_after(wavefront, coordinates.q(), parameters)

        return wavefront
'''

So far so good, I can propagate the full beamline with settings for each individual element....
But I want more, see next issue!!

**Comment by srio** [comment]
Now I want to be able to propagate a beamline using a different propagator for each element. 
For example, a 1D beamline of two elements, one using the zoom and the other the integral. 

Presently is not possible, because there are two nested loops. The outer one (the chain of responsibility in PropagationManager.do_propagation()) goes trough all the different propagator handlers. The inner one in Propagator.do_propagation()  runs over the beamline elements. 

Would be possible (and elegant) to invert the order of the loops? For example, do nothing in AbstractPropagator.do_propagator() and  insert the chain of responsibility loop inside the loop in Propagator.do_propagation()?

My example should look as: 

```
    from wofry.propagator.propagator import PropagationElements
    from wofry.propagator.propagator import PropagationParameters

    propagation_elements = PropagationElements()

    element1_parameters = {'shift_half_pixel' : 1, 
                           'magnification_x': magnification_x1, 
                           'magnification_y': magnification_y1}
    element2_parameters = {'shift_half_pixel' : 1, 
                           'magnification_x': magnification_x2, 
                           'magnification_y': magnification_y2}

    propagation_elements.add_beamline_element(beamline_element1, element1_parameters,
         handler_name=FresnelZoom1D.HANDLER_NAME)
    propagation_elements.add_beamline_element(beamline_element2, element2_parameters, 
        handler_name=Integral1D.HANDLER_NAME) # etc etc

    propagation_parameters = PropagationParameters(wavefront=input_wavefront.duplicate(),propagation_elements = propagation_elements)

```
Thanks!!!

**Comment by lucarebuffi** [comment]
You can do it now by splitting the beamline and using different propagators. Anyway, by modifying the AbstractPropagator class we can do this upgrade quite easily. I will come back on this asap.

**Comment by srio** [comment]
Now all the propagation mechanism for dealing with additional parameters has been restructured. There are two ways of defining parameters, the traditional way:

'''
            propagation_elements.add_beamline_element(BeamlineElement(optical_element=slit,
                                                                      coordinates=ElementCoordinates(p=0, q=propagation_distance)))


            propagator = PropagationManager.Instance()
            propagation_parameters = PropagationParameters(wavefront=wf,
                                                           propagation_elements=propagation_elements)


            propagation_parameters.set_additional_parameters("shift_half_pixel", True)
            propagation_parameters.set_additional_parameters("magnification_x", 2.0)
            propagation_parameters.set_additional_parameters("magnification_y", 0.5)
            wf1 = propagator.do_propagation(propagation_parameters, FresnelZoomXY2D.HANDLER_NAME)
'''

and the new one, that allows to specify parameters element by element:

'''

            additional_parameters = {"shift_half_pixel":True,
                                         "magnification_x":2.0,
                                         "magnification_y":0.5}
            propagation_elements.add_beamline_element(
                        BeamlineElement(optical_element=slit,coordinates=ElementCoordinates(p=0, q=propagation_distance)),
                        element_parameters=additional_parameters)


            propagator = PropagationManager.Instance()
            propagation_parameters = PropagationParameters(wavefront=wf,
                                                           propagation_elements=propagation_elements)

            wf1 = propagator.do_propagation(propagation_parameters, FresnelZoomXY2D.HANDLER_NAME)
''' 


The propagators have been modified to adapt this new structure. A new method has been added to Propagator. In case of conflict (the same additional parameter defined in both new and old way), it gives priority to the new way:

'''
    def get_additional_parameter(self, parameter_name, default_value, propagation_parameters, element_index=None, ):
        value = default_value
        try:
            value = propagation_parameters.get_additional_parameter(parameter_name)
        except:
            pass

        if element_index is None:
            myindex = 0
        else:
            myindex = element_index

        parameters_dict = propagation_parameters.get_PropagationElements().get_propagation_element_parameter(myindex)

        if parameters_dict is not None:
            if parameter_name in parameters_dict.keys():
                value = parameters_dict[parameter_name]

        return value
'''


Please note that "element_index" is not passed to the Optical elements (not needed and it would force to change the signature of all wofry beamline elements). The loop in Propagator is:

'''
        for index in range(0, parameters.get_PropagationElements().get_propagation_elements_number()):
            element = parameters.get_PropagationElements().get_propagation_element(index)
            coordinates = element.get_coordinates()

            if coordinates.p() != 0.0: wavefront = self.do_specific_progation_before(wavefront, coordinates.p(), parameters, element_index=index)
            wavefront = element.get_optical_element().applyOpticalElement(wavefront, parameters)
            if coordinates.q() != 0.0: wavefront = self.do_specific_progation_after(wavefront, coordinates.q(), parameters, element_index=index)

'''

**Comment by lucarebuffi** [comment]
I added the element index to the method applyOpticalElement (and modified all the wofry beamline elements), since software like SRW have different sets of parameters for the drift space and the optical element. In principle it could be useful to have the access of them in every phase of the propagation process.

See: 
https://github.com/oasys-kit/wofry/commit/1dae172436b83bdd28622746a06565fbc4eb0fcc
